/* 주소 */
CREATE TABLE ADDRESSES (
    ADDR_ID NUMBER NOT NULL, /* 주소코드 */
    STREET VARCHAR2(50) NOT NULL, /* 도로 */
    CITY VARCHAR2(50) NOT NULL, /* 시 */
    STATE VARCHAR2(50) NOT NULL, /* 구 */
    ZIP VARCHAR2(10), /* 우편번호 */
    COUNTRY VARCHAR2(50) NOT NULL /* 읍 */
);
ALTER TABLE ADDRESSES ADD  CONSTRAINT PK_ADDRESS_ID  PRIMARY KEY (ADDR_ID);


/* 과목 */
CREATE TABLE COURSES (
    COURSE_ID NUMBER NOT NULL, /* 과목코드 */
    NAME VARCHAR2(100) NOT NULL, /* 과목명 */
    DESCRIPTION VARCHAR2(512), /* 설명 */
    START_DATE DATE, /* 시작일 */
    END_DATE DATE, /* 종료일 */
    TUTOR_ID NUMBER NOT NULL /* 교수번호 */
);
ALTER TABLE COURSES ADD CONSTRAINT PK_COURSE_ID PRIMARY KEY (COURSE_ID);

/* 수강등록 */
CREATE TABLE COURSE_ENROLLMENT (
    COURSE_ID NUMBER NOT NULL, /* 과목코드 */
    STUD_ID NUMBER NOT NULL /* 학생코드 */
);
ALTER TABLE COURSE_ENROLLMENT ADD CONSTRAINT PK_COURSE_ENROLL_CID_SID PRIMARY KEY (COURSE_ID, STUD_ID);

/* 학생 */
CREATE TABLE STUDENTS (
    STUD_ID NUMBER NOT NULL, /* 학생코드 */
    NAME VARCHAR2(50) NOT NULL, /* 이름 */
    EMAIL VARCHAR2(50) NOT NULL, /* 이메일 */
    PHONE NCHAR(13), /* 연락처 */
    DOB DATE, /* 생일 */
    BIO CLOB, /* 자기소개 */
    PIC BLOB, /* 사진 */
    ADDR_ID NUMBER /* 주소코드 */
);

ALTER TABLE STUDENTS ADD CONSTRAINT PK_STUDENT_ID PRIMARY KEY (STUD_ID);

/* 교수 */
CREATE TABLE TUTORS (
    TUTOR_ID NUMBER NOT NULL, /* 교수번호 */
    NAME VARCHAR2(50) NOT NULL, /* 이름 */
    EMAIL VARCHAR2(50) NOT NULL, /* 이메일 */
    PHONE NCHAR(13), /* 연락처 */
    DOB DATE, /* 생일 */
    BIO CLOB, /* 자기소개 */
    PIC BLOB, /* 사진 */
    ADDR_ID NUMBER /* 주소코드 */
);

ALTER TABLE TUTORS ADD CONSTRAINT PRIMARY PRIMARY KEY (TUTOR_ID);
ALTER TABLE COURSES ADD CONSTRAINT FK_COURSE_TUTOR FOREIGN KEY (TUTOR_ID)  REFERENCES TUTORS (TUTOR_ID);
ALTER TABLE COURSE_ENROLLMENT ADD CONSTRAINT FK_ENROLLMENT_COURSE FOREIGN KEY (COURSE_ID) REFERENCES COURSES (COURSE_ID);
ALTER TABLE COURSE_ENROLLMENT ADD CONSTRAINT FK_ENROLLMENT_STUD FOREIGN KEY (STUD_ID) REFERENCES STUDENTS (STUD_ID);
ALTER TABLE STUDENTS ADD CONSTRAINT FK_STUDENTS_ADDR FOREIGN KEY ( ADDR_ID ) REFERENCES ADDRESSES (ADDR_ID);
ALTER TABLE TUTORS ADD CONSTRAINT FK_TUTORS_ADDR FOREIGN KEY (ADDR_ID) REFERENCES ADDRESSES ( ADDR_ID );

