SELECT * FROM USER_TABLES;

SELECT * FROM ADDRESSES;
SELECT * FROM STUDENTS;
SELECT * FROM COURSES;
SELECT STUD_ID AS STUDID, NAME, EMAIL, PHONE, DOB FROM STUDENTS WHERE STUD_ID = 1;

SELECT STUD_ID, NAME, EMAIL, DOB, SUBSTR(PHONE, 1, 3) AS F, SUBSTR(PHONE, 5, 3) AS M, SUBSTR(PHONE, 9, 4) AS L FROM STUDENTS WHERE STUD_ID = 1;

INSERT INTO STUDENTS(STUD_ID, NAME, EMAIL, PHONE, DOB) VALUES(3, 'Thomas', 'thomas@gmail.com', '444-555-6666', '1988-01-16');

UPDATE STUDENTS SET NAME = 'Pong', EMAIL = 'Pong@gmail.com', PHONE = '111-2222-4444' WHERE STUD_ID = 4; 

DELETE FROM STUDENTS WHERE STUD_ID = 4;

SELECT STUD_ID, NAME, EMAIL, PHONE, DOB, A.ADDR_ID, STREET, CITY, STATE, ZIP, COUNTRY
  FROM STUDENTS S JOIN ADDRESSES A ON S.ADDR_ID=A.ADDR_ID
 WHERE STUD_ID = 1;
 
SELECT T.TUTOR_ID, T.NAME AS TUTOR_NAME, EMAIL, C.COURSE_ID, C.NAME, DESCRIPTION, START_DATE, END_DATE
  FROM TUTORS T LEFT OUTER JOIN COURSES C ON T.TUTOR_ID=C.TUTOR_ID
 WHERE T.TUTOR_ID = 1;